default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: <%= ENV.fetch('DATABASE_HOST') %>

development:
  <<: *default
  database: fabnavi5_development

test:
  <<: *default
  database: fabnavi5_test
